# theme: jekyll-theme-slate
title: Argo's Space
description: Here are my learning notes
baseurl: /publishNotes
markdown: kramdown
plugins:
  - jekyll-remote-theme
remote_theme: benbalter/retlab